// Every entry below was verified against a live public career-board endpoint.
// Add new employers only after confirming that their board returns published jobs.
module.exports = [
    // Core technology employers
    { company: "Google", provider: "google", board: "google-careers", careerUrl: "https://www.google.com/about/careers/applications/jobs/results/", group: "core" },
    { company: "OpenAI", provider: "ashby", board: "openai", group: "core" },
    { company: "Notion", provider: "ashby", board: "notion", group: "core" },
    { company: "Ramp", provider: "ashby", board: "ramp", group: "core" },
    { company: "Linear", provider: "ashby", board: "linear", group: "core" },
    { company: "Cursor", provider: "ashby", board: "cursor", group: "core" },
    { company: "Cloudflare", provider: "greenhouse", board: "cloudflare", group: "core" },
    { company: "Datadog", provider: "greenhouse", board: "datadog", group: "core" },
    { company: "MongoDB", provider: "greenhouse", board: "mongodb", group: "core" },
    { company: "Figma", provider: "greenhouse", board: "figma", group: "core" },
    { company: "Samsara", provider: "greenhouse", board: "samsara", group: "core" },
    { company: "Stripe", provider: "greenhouse", board: "stripe", group: "core" },
    { company: "Reddit", provider: "greenhouse", board: "reddit", group: "core" },
    { company: "Dropbox", provider: "greenhouse", board: "dropbox", group: "core" },
    { company: "Palantir", provider: "lever", board: "palantir", group: "core" },

    // Large and publicly traded technology employers
    { company: "Airbnb", provider: "greenhouse", board: "airbnb", group: "major" },
    { company: "Affirm", provider: "greenhouse", board: "affirm", group: "major" },
    { company: "Asana", provider: "greenhouse", board: "asana", group: "major" },
    { company: "Block", provider: "greenhouse", board: "block", group: "major" },
    { company: "Coinbase", provider: "greenhouse", board: "coinbase", group: "major" },
    { company: "Discord", provider: "greenhouse", board: "discord", group: "major" },
    { company: "DoorDash", provider: "greenhouse", board: "doordashusa", group: "major" },
    { company: "Duolingo", provider: "greenhouse", board: "duolingo", group: "major" },
    { company: "Elastic", provider: "greenhouse", board: "elastic", group: "major" },
    { company: "Flexport", provider: "greenhouse", board: "flexport", group: "major" },
    { company: "GitLab", provider: "greenhouse", board: "gitlab", group: "major" },
    { company: "HubSpot", provider: "greenhouse", board: "hubspotjobs", group: "major" },
    { company: "Instacart", provider: "greenhouse", board: "instacart", group: "major" },
    { company: "Klaviyo", provider: "greenhouse", board: "klaviyo", group: "major" },
    { company: "Lucid Motors", provider: "greenhouse", board: "lucidmotors", group: "major" },
    { company: "Lyft", provider: "greenhouse", board: "lyft", group: "major" },
    { company: "Okta", provider: "greenhouse", board: "okta", group: "major" },
    { company: "Pinterest", provider: "greenhouse", board: "pinterest", group: "major" },
    { company: "Robinhood", provider: "greenhouse", board: "robinhood", group: "major" },
    { company: "Roblox", provider: "greenhouse", board: "roblox", group: "major" },
    { company: "Toast", provider: "greenhouse", board: "toast", group: "major" },
    { company: "Tripadvisor", provider: "greenhouse", board: "tripadvisor", group: "major" },
    { company: "Twilio", provider: "greenhouse", board: "twilio", group: "major" },
    { company: "Perplexity", provider: "ashby", board: "perplexity", group: "major" },
    { company: "Spotify", provider: "lever", board: "spotify", group: "major" },

    // Live company boards referenced by SimplifyJobs/New-Grad-Positions
    { company: "Alarm.com", provider: "greenhouse", board: "alarmcom", group: "simplify" },
    { company: "Allen Control Systems", provider: "ashby", board: "allen-control-systems", group: "simplify" },
    { company: "Alphataraxia", provider: "greenhouse", board: "alphataraxia", group: "simplify" },
    { company: "Anduril", provider: "greenhouse", board: "andurilindustries", group: "simplify" },
    { company: "Antares Nuclear", provider: "ashby", board: "Antares", group: "simplify" },
    { company: "Applied Intuition", provider: "ashby", board: "applied", group: "simplify" },
    { company: "Aquatic Capital Management", provider: "greenhouse", board: "aquaticcapitalmanagement", group: "simplify" },
    { company: "Atoms", provider: "greenhouse", board: "cssmerge", group: "simplify" },
    { company: "Backbone Systems", provider: "ashby", board: "backbone", group: "simplify" },
    { company: "Bloxd", provider: "ashby", board: "bloxd", group: "simplify" },
    { company: "Brain Co.", provider: "ashby", board: "brainco", group: "simplify" },
    { company: "Bridger", provider: "ashby", board: "bridger", group: "simplify" },
    { company: "Captivation", provider: "greenhouse", board: "captivation", group: "simplify" },
    { company: "CarbonChain", provider: "greenhouse", board: "carbonchain", group: "simplify" },
    { company: "Cerebras", provider: "ashby", board: "cerebras", group: "simplify" },
    { company: "Color", provider: "ashby", board: "color-health", group: "simplify" },
    { company: "Composio", provider: "ashby", board: "composio", group: "simplify" },
    { company: "Confido", provider: "ashby", board: "confido", group: "simplify" },
    { company: "Cortica", provider: "greenhouse", board: "allcareers", group: "simplify" },
    { company: "Corvus Robotics", provider: "ashby", board: "corvus-robotics", group: "simplify" },
    { company: "Crusoe", provider: "ashby", board: "Crusoe", group: "simplify" },
    { company: "Cybernetic Labs", provider: "ashby", board: "netic", group: "simplify" },
    { company: "Cylake", provider: "ashby", board: "cylake-inc", group: "simplify" },
    { company: "Dark Wolf Solutions", provider: "greenhouse", board: "darkwolfsolutions", group: "simplify" },
    { company: "Datalab USA", provider: "lever", board: "datalabusa", group: "simplify" },
    { company: "Deliveroo", provider: "ashby", board: "deliveroo", group: "simplify" },
    { company: "Ellipsis Labs", provider: "ashby", board: "ellipsislabs", group: "simplify" },
    { company: "Faros AI", provider: "ashby", board: "faros-ai", group: "simplify" },
    { company: "Firetiger", provider: "ashby", board: "firetiger", group: "simplify" },
    { company: "Flow Engineering", provider: "ashby", board: "flowengineering", group: "simplify" },
    { company: "Freeform", provider: "greenhouse", board: "freeformfuturecorp", group: "simplify" },
    { company: "General Matter", provider: "greenhouse", board: "generalmatter", group: "simplify" },
    { company: "Giga AI", provider: "ashby", board: "gigaml", group: "simplify" },
    { company: "Hatch IT", provider: "lever", board: "hatchit", group: "simplify" },
    { company: "Hiive", provider: "ashby", board: "hiive", group: "simplify" },
    { company: "Hipp Health", provider: "ashby", board: "hipp", group: "simplify" },
    { company: "Icon", provider: "ashby", board: "icon", group: "simplify" },
    { company: "Inductive Automation", provider: "ashby", board: "inductive-automation-llc", group: "simplify" },
    { company: "InstaLILY", provider: "greenhouse", board: "instalilyai", group: "simplify" },
    { company: "Julius AI", provider: "ashby", board: "julius", group: "simplify" },
    { company: "Kikoff", provider: "greenhouse", board: "kikoff", group: "simplify" },
    { company: "Koah", provider: "ashby", board: "koahlabs", group: "simplify" },
    { company: "Lightfield", provider: "ashby", board: "Lightfield", group: "simplify" },
    { company: "Mach Industries", provider: "ashby", board: "mach", group: "simplify" },
    { company: "Maven Securities", provider: "greenhouse", board: "mavensecuritiesholdingltd", group: "simplify" },
    { company: "Maximor AI", provider: "ashby", board: "maximor", group: "simplify" },
    { company: "N1", provider: "ashby", board: "n1", group: "simplify" },
    { company: "NewsBreak", provider: "greenhouse", board: "newsbreak", group: "simplify" },
    { company: "Nooks", provider: "ashby", board: "nooks", group: "simplify" },
    { company: "Northwood Space", provider: "ashby", board: "NorthwoodSpace", group: "simplify" },
    { company: "Observable Space", provider: "ashby", board: "observable-space", group: "simplify" },
    { company: "Parallel Web Systems", provider: "ashby", board: "parallel", group: "simplify" },
    { company: "Pariveda Solutions", provider: "ashby", board: "pariveda", group: "simplify" },
    { company: "People Culture Talent", provider: "ashby", board: "people-culture-talent", group: "simplify" },
    { company: "Preference Model", provider: "ashby", board: "Preference-Model", group: "simplify" },
    { company: "Pylon", provider: "ashby", board: "pylon-labs", group: "simplify" },
    { company: "Quora", provider: "ashby", board: "quora", group: "simplify" },
    { company: "Realm", provider: "ashby", board: "realmalliance", group: "simplify" },
    { company: "Retell AI", provider: "ashby", board: "retell-ai", group: "simplify" },
    { company: "Revel", provider: "ashby", board: "revel", group: "simplify" },
    { company: "Rocket Lab USA", provider: "greenhouse", board: "rocketlab", group: "simplify" },
    { company: "Rollout", provider: "ashby", board: "rollout", group: "simplify" },
    { company: "RunSybil", provider: "ashby", board: "runsybil-jobs", group: "simplify" },
    { company: "SentiLink", provider: "ashby", board: "sentilink", group: "simplify" },
    { company: "Sigma Computing", provider: "greenhouse", board: "sigmacomputing", group: "simplify" },
    { company: "SimpliSafe", provider: "greenhouse", board: "simplisafe", group: "simplify" },
    { company: "Snowflake", provider: "ashby", board: "snowflake", group: "simplify" },
    { company: "Solace Health", provider: "ashby", board: "solace", group: "simplify" },
    { company: "SpaceX", provider: "greenhouse", board: "spacex", group: "simplify" },
    { company: "SteerBridge", provider: "lever", board: "steerbridge", group: "simplify" },
    { company: "Strada", provider: "ashby", board: "stradahq", group: "simplify" },
    { company: "Tax Relief Advocates", provider: " ggreenhouse", board: "taxreliefadvocates", group: "simplify" },
    { company: "Torc Robotics", provider: "greenhouse", board: "torcrobotics", group: "simplify" },
    { company: "Tracebit", provider: "ashby", board: "tracebit", group: "simplify" },
    { company: "TransMarket Group", provider: "greenhouse", board: "transmarketgroup", group: "simplify" },
    { company: "True Anomaly", provider: "greenhouse", board: "trueanomalyinc", group: "simplify" },
    { company: "Uare.ai", provider: "greenhouse", board: "uareai", group: "simplify" },
    { company: "Uncountable", provider: "ashby", board: "uncountable", group: "simplify" },
    { company: "Uniswap", provider: "ashby", board: "uniswap", group: "simplify" },
    { company: "WeRide", provider: "lever", board: "weride", group: "simplify" },
    { company: "Wonderschool", provider: "greenhouse", board: "wonderschool", group: "simplify" },
    { company: "Wyetech", provider: "lever", board: "wyetechllc", group: "simplify" },
    { company: "Zip", provider: "ashby", board: "zip", group: "simplify" },
    { company: "Zone 5 Technologies", provider: "greenhouse", board: "zone5technologies", group: "simplify" },
];
