// Every entry below was verified against a live public career-board endpoint.
// Add new employers only after confirming that their board returns published jobs.
module.exports = [
    // Core technology employers
    { company: "Google", provider: "google", board: "google-careers", careerUrl: "https://www.google.com/about/careers/applications/jobs/results/", group: "core" },
    { company: "OpenAI", provider: "ashby", board: "openai", group: "core" },
    { company: "Notion", provider: "ashby", board: "notion", group: "core" },
    { company: "Ramp", provider: "ashby", board: "ramp", group: "core" },
    { company: "Linear", provider: "ashby", board: "linear", group: "core" },
    { company: "Cursor", provider: "ashby", board: "cursor", group: "core" },
    { company: "Cloudflare", provider: "greenhouse", board: "cloudflare", group: "core" },
    { company: "Datadog", provider: "greenhouse", board: "datadog", group: "core" },
    { company: "MongoDB", provider: "greenhouse", board: "mongodb", group: "core" },
    { company: "Figma", provider: "greenhouse", board: "figma", group: "core" },
    { company: "Samsara", provider: "greenhouse", board: "samsara", group: "core" },
    { company: "Stripe", provider: "greenhouse", board: "stripe", group: "core" },
    { company: "Reddit", provider: "greenhouse", board: "reddit", group: "core" },
    { company: "Dropbox", provider: "greenhouse", board: "dropbox", group: "core" },
    { company: "Palantir", provider: "lever", board: "palantir", group: "core" },

    // Large and publicly traded technology employers
    { company: "Airbnb", provider: "greenhouse", board: "airbnb", group: "major" },
    { company: "Affirm", provider: "greenhouse", board: "affirm", group: "major" },
    { company: "Asana", provider: "greenhouse", board: "asana", group: "major" },
    { company: "Block", provider: "greenhouse", board: "block", group: "major" },
    { company: "Coinbase", provider: "greenhouse", board: "coinbase", group: "major" },
    { company: "Discord", provider: "greenhouse", board: "discord", group: "major" },
    { company: "DoorDash", provider: "greenhouse", board: "doordashusa", group: "major" },
    { company: "Duolingo", provider: "greenhouse", board: "duolingo", group: "major" },
    { company: "Elastic", provider: "greenhouse", board: "elastic", group: "major" },
    { company: "Flexport", provider: "greenhouse", board: "flexport", group: "major" },
    { company: "GitLab", provider: "greenhouse", board: "gitlab", group: "major" },
    { company: "HubSpot", provider: "greenhouse", board: "hubspotjobs", group: "major" },
    { company: "Instacart", provider: "greenhouse", board: "instacart", group: "major" },
    { company: "Klaviyo", provider: "greenhouse", board: "klaviyo", group: "major" },
    { company: "Lucid Motors", provider: "greenhouse", board: "lucidmotors", group: "major" },
    { company: "Lyft", provider: "greenhouse", board: "lyft", group: "major" },
    { company: "Okta", provider: "greenhouse", board: "okta", group: "major" },
    { company: "Pinterest", provider: "greenhouse", board: "pinterest", group: "major" },
    { company: "Robinhood", provider: "greenhouse", board: "robinhood", group: "major" },
    { company: "Roblox", provider: "greenhouse", board: "roblox", group: "major" },
    { company: "Toast", provider: "greenhouse", board: "toast", group: "major" },
    { company: "Tripadvisor", provider: "greenhouse", board: "tripadvisor", group: "major" },
    { company: "Twilio", provider: "greenhouse", board: "twilio", group: "major" },
    { company: "Perplexity", provider: "ashby", board: "perplexity", group: "major" },
    { company: "Spotify", provider: "lever", board: "spotify", group: "major" },

    // Live company boards referenced by SimplifyJobs/New-Grad-Positions
    { company: "Alarm.com", provider: "greenhouse", board: "alarmcom", group: "simplify" },
    { company: "Allen Control Systems", provider: "ashby", board: "allen-control-systems", group: "simplify" },
    { company: "Alphataraxia", provider: "greenhouse", board: "alphataraxia", group: "simplify" },
    { company: "Anduril", provider: "greenhouse", board: "andurilindustries", group: "simplify" },
    { company: "Antares Nuclear", provider: "ashby", board: "Antares", group: "simplify" },
    { company: "Applied Intuition", provider: "ashby", board: "applied", group: "simplify" },
    { company: "Aquatic Capital Management", provider: "greenhouse", board: "aquaticcapitalmanagement", group: "simplify" },
    { company: "Atoms", provider: "greenhouse", board: "cssmerge", group: "simplify" },
    { company: "Backbone Systems", provider: "ashby", board: "backbone", group: "simplify" },
    { company: "Bloxd", provider: "ashby", board: "bloxd", group: "simplify" },
    { company: "Brain Co.", provider: "ashby", board: "brainco", group: "simplify" },
    { company: "Bridger", provider: "ashby", board: "bridger", group: "simplify" },
    { company: "Captivation", provider: "greenhouse", board: "captivation", group: "simplify" },
    { company: "CarbonChain", provider: "greenhouse", board: "carbonchain", group: "simplify" },
    { company: "Cerebras", provider: "ashby", board: "cerebras", group: "simplify" },
    { company: "Color", provider: "ashby", board: "color-health", group: "simplify" },
    { company: "Composio", provider: "ashby", board: "composio", group: "simplify" },
    { company: "Confido", provider: "ashby", board: "confido", group: "simplify" },
    { company: "Cortica", provider: "greenhouse", board: "allcareers", group: "simplify" },
    { company: "Corvus Robotics", provider: "ashby", board: "corvus-robotics", group: "simplify" },
    { company: "Crusoe", provider: "ashby", board: "Crusoe", group: "simplify" },
    { company: "Cybernetic Labs", provider: "ashby", board: "netic", group: "simplify" },
    { company: "Cylake", provider: "ashby", board: "cylake-inc", group: "simplify" },
    { company: "Dark Wolf Solutions", provider: "greenhouse", board: "darkwolfsolutions", group: "simplify" },
    { company: "Datalab USA", provider: "lever", board: "datalabusa", group: "simplify" },
    { company: "Deliveroo", provider: "ashby", board: "deliveroo", group: "simplify" },
    { company: "Ellipsis Labs", provider: "ashby", board: "ellipsislabs", group: "simplify" },
    { company: "Faros AI", provider: "ashby", board: "faros-ai", group: "simplify" },
    { company: "Firetiger", provider: "ashby", board: "firetiger", group: "simplify" },
    { company: "Flow Engineering", provider: "ashby", board: "flowengineering", group: "simplify" },
    { company: "Freeform", provider: "greenhouse", board: "freeformfuturecorp", group: "simplify" },
    { company: "General Matter", provider: "greenhouse", board: "generalmatter", group: "simplify" },
    { company: "Giga AI", provider: "ashby", board: "gigaml", group: "simplify" },
    { company: "Hatch IT", provider: "lever", board: "hatchit", group: "simplify" },
    { company: "Hiive", provider: "ashby", board: "hiive", group: "simplify" },
    { company: "Hipp Health", provider: "ashby", board: "hipp", group: "simplify" },
    { company: "Icon", provider: "ashby", board: "icon", group: "simplify" },
    { company: "Inductive Automation", provider: "ashby", board: "inductive-automation-llc", group: "simplify" },
    { company: "InstaLILY", provider: "greenhouse", board: "instalilyai", group: "simplify" },
    { company: "Julius AI", provider: "ashby", board: "julius", group: "simplify" },
    { company: "Kikoff", provider: "greenhouse", board: "kikoff", group: "simplify" },
    { company: "Koah", provider: "ashby", board: "koahlabs", group: "simplify" },
    { company: "Lightfield", provider: "ashby", board: "Lightfield", group: "simplify" },
    { company: "Mach Industries", provider: "ashby", board: "mach", group: "simplify" },
    { company: "Maven Securities", provider: "greenhouse", board: "mavensecuritiesholdingltd", group: "simplify" },
    { company: "Maximor AI", provider: "ashby", board: "maximor", group: "simplify" },
    { company: "N1", provider: "ashby", board: "n1", group: "simplify" },
    { company: "NewsBreak", provider: "greenhouse", board: "newsbreak", group: "simplify" },
    { company: "Nooks", provider: "ashby", board: "nooks", group: "simplify" },
    { company: "Northwood Space", provider: "ashby", board: "NorthwoodSpace", group: "simplify" },
    { company: "Observable Space", provider: "ashby", board: "observable-space", group: "simplify" },
    { company: "Parallel Web Systems", provider: "ashby", board: "parallel", group: "simplify" },
    { company: "Pariveda Solutions", provider: "ashby", board: "pariveda", group: "simplify" },
    { company: "People Culture Talent", provider: "ashby", board: "people-culture-talent", group: "simplify" },
    { company: "Preference Model", provider: "ashby", board: "Preference-Model", group: "simplify" },
    { company: "Pylon", provider: "ashby", board: "pylon-labs", group: "simplify" },
    { company: "Quora", provider: "ashby", board: "quora", group: "simplify" },
    { company: "Realm", provider: "ashby", board: "realmalliance", group: "simplify" },
    { company: "Retell AI", provider: "ashby", board: "retell-ai", group: "simplify" },
    { company: "Revel", provider: "ashby", board: "revel", group: "simplify" },
    { company: "Rocket Lab USA", provider: "greenhouse", board: "rocketlab", group: "simplify" },
    { company: "Rollout", provider: "ashby", board: "rollout", group: "simplify" },
    { company: "RunSybil", provider: "ashby", board: "runsybil-jobs", group: "simplify" },
    { company: "SentiLink", provider: "ashby", board: "sentilink", group: "simplify" },
    { company: "Sigma Computing", provider: "greenhouse", board: "sigmacomputing", group: "simplify" },
    { company: "SimpliSafe", provider: "greenhouse", board: "simplisafe", group: "simplify" },
    { company: "Snowflake", provider: "ashby", board: "snowflake", group: "simplify" },
    { company: "Solace Health", provider: "ashby", board: "solace", group: "simplify" },
    { company: "SpaceX", provider: "greenhouse", board: "spacex", group: "simplify" },
    { company: "SteerBridge", provider: "lever", board: "steerbridge", group: "simplify" },
    { company: "Strada", provider: "ashby", board: "stradahq", group: "simplify" },
    { company: "Tax Relief Advocates", provider: " ggreenhouse", board: "taxreliefadvocates", group: "simplify" },
    { company: "Torc Robotics", provider: "greenhouse", board: "torcrobotics", group: "simplify" },
    { company: "Tracebit", provider: "ashby", board: "tracebit", group: "simplify" },
    { company: "TransMarket Group", provider: "greenhouse", board: "transmarketgroup", group: "simplify" },
    { company: "True Anomaly", provider: "greenhouse", board: "trueanomalyinc", group: "simplify" },
    { company: "Uare.ai", provider: "greenhouse", board: "uareai", group: "simplify" },
    { company: "Uncountable", provider: "ashby", board: "uncountable", group: "simplify" },
    { company: "Uniswap", provider: "ashby", board: "uniswap", group: "simplify" },
    { company: "WeRide", provider: "lever", board: "weride", group: "simplify" },
    { company: "Wonderschool", provider: "greenhouse", board: "wonderschool", group: "simplify" },
    { company: "Wyetech", provider: "lever", board: "wyetechllc", group: "simplify" },
    { company: "Zip", provider: "ashby", board: "zip", group: "simplify" },
    { company: "Zone 5 Technologies", provider: "greenhouse", board: "zone5technologies", group: "simplify" },
    { company: "3RedPartners", provider: "greenhouse", board: "3redpartners", group: "verified-us-swe" },
    { company: "Accenture Federal Services", provider: "greenhouse", board: "accenturefederalservices", group: "verified-us-swe" },
    { company: "Agile Defense", provider: "lever", board: "agile-defense", group: "verified-us-swe" },
    { company: "AnaVation", provider: "lever", board: "anavationllc", group: "verified-us-swe" },
    { company: "Appian", provider: "greenhouse", board: "appian", group: "verified-us-swe" },
    { company: "Architect Labs", provider: "ashby", board: "architect", group: "verified-us-swe" },
    { company: "Argmax", provider: "greenhouse", board: "argmax", group: "verified-us-swe" },
    { company: "Artera", provider: "lever", board: "artera-2", group: "verified-us-swe" },
    { company: "ASSYST", provider: "greenhouse", board: "assystinc", group: "verified-us-swe" },
    { company: "Astera", provider: "ashby", board: "astera", group: "verified-us-swe" },
    { company: "Base Power", provider: "ashby", board: "base-power", group: "verified-us-swe" },
    { company: "Belvedere Trading", provider: "lever", board: "belvederetrading", group: "verified-us-swe" },
    { company: "Binance.US", provider: "ashby", board: "binance.us", group: "verified-us-swe" },
    { company: "Boson AI", provider: "lever", board: "bosonai", group: "verified-us-swe" },
    { company: "Bot Auto", provider: "greenhouse", board: "botauto", group: "verified-us-swe" },
    { company: "BTI360", provider: "greenhouse", board: "bti36021", group: "verified-us-swe" },
    { company: "Canonical", provider: "greenhouse", board: "canonical", group: "verified-us-swe" },
    { company: "Capco", provider: "greenhouse", board: "capco", group: "verified-us-swe" },
    { company: "Carefeed", provider: "greenhouse", board: "carefeed", group: "verified-us-swe" },
    { company: "Casino Cash Trac", provider: "lever", board: "casino-cash-trac", group: "verified-us-swe" },
    { company: "Centerfield", provider: "ashby", board: "centerfield", group: "verified-us-swe" },
    { company: "Chicago Trading Company Campus", provider: "greenhouse", board: "chicagotradingcampus", group: "verified-us-swe" },
    { company: "Chicago Trading Company", provider: "greenhouse", board: "ctccampusboard", group: "verified-us-swe" },
    { company: "Clarity Innovations", provider: "greenhouse", board: "clarityinnovates", group: "verified-us-swe" },
    { company: "Compeer Financial", provider: "greenhouse", board: "compeerfinancial", group: "verified-us-swe" },
    { company: "Cook Systems", provider: "greenhouse", board: "cooksys", group: "verified-us-swe" },
    { company: "Creatify", provider: "ashby", board: "creatify", group: "verified-us-swe" },
    { company: "Dexmate", provider: "ashby", board: "dexmate", group: "verified-us-swe" },
    { company: "Docugami", provider: "greenhouse", board: "docugami", group: "verified-us-swe" },
    { company: "Dome Systems", provider: "ashby", board: "dome-systems-inc", group: "verified-us-swe" },
    { company: "DRW", provider: "greenhouse", board: "drweng", group: "verified-us-swe" },
    { company: "DV Trading", provider: "greenhouse", board: "dvtrading", group: "verified-us-swe" },
    { company: "Eliza", provider: "ashby", board: "eliza", group: "verified-us-swe" },
    { company: "Emerald AI", provider: "ashby", board: "emerald-ai", group: "verified-us-swe" },
    { company: "Endeavor AI", provider: "ashby", board: "endeavorai", group: "verified-us-swe" },
    { company: "Etched", provider: "ashby", board: "Etched", group: "verified-us-swe" },
    { company: "Evolver", provider: "greenhouse", board: "evolver", group: "verified-us-swe" },
    { company: "Fab2", provider: "ashby", board: "fab2", group: "verified-us-swe" },
    { company: "Foundation Health", provider: "ashby", board: "foundationhealthcareers", group: "verified-us-swe" },
    { company: "FSH Technologies", provider: "ashby", board: "FSH", group: "verified-us-swe" },
    { company: "Ginkgo Bioworks", provider: "greenhouse", board: "ginkgobioworks", group: "verified-us-swe" },
    { company: "Glide", provider: "ashby", board: "glide", group: "verified-us-swe" },
    { company: "Global Lending Services", provider: "lever", board: "glsllc", group: "verified-us-swe" },
    { company: "Hermeus", provider: "lever", board: "hermeus", group: "verified-us-swe" },
    { company: "HHAeXchange", provider: "lever", board: "hhaexchange", group: "verified-us-swe" },
    { company: "Hyannis Port Research", provider: "greenhouse", board: "hyannisportresearch", group: "verified-us-swe" },
    { company: "impact.com", provider: "greenhouse", board: "impact", group: "verified-us-swe" },
    { company: "Incident IQ", provider: "greenhouse", board: "incidentiq", group: "verified-us-swe" },
    { company: "ITS Logistics", provider: "greenhouse", board: "itslogisticsllc", group: "verified-us-swe" },
    { company: "k-ID", provider: "ashby", board: "k-id", group: "verified-us-swe" },
    { company: "KAYAK", provider: "ashby", board: "KAYAK", group: "verified-us-swe" },
    { company: "Kognitos", provider: "ashby", board: "Kognitos", group: "verified-us-swe" },
    { company: "LiteLLM", provider: "ashby", board: "litellm", group: "verified-us-swe" },
    { company: "LiveFlow", provider: "ashby", board: "liveflow", group: "verified-us-swe" },
    { company: "Lynk", provider: "ashby", board: "Lynk", group: "verified-us-swe" },
    { company: "Makai Labs", provider: "ashby", board: "makai-labs", group: "verified-us-swe" },
    { company: "Maxima", provider: "ashby", board: "maxima", group: "verified-us-swe" },
    { company: "McMaster-Carr", provider: "greenhouse", board: "mcmastercarr", group: "verified-us-swe" },
    { company: "Medical Informatics Engineering", provider: "greenhouse", board: "medicalinformaticsengineering", group: "verified-us-swe" },
    { company: "Meridian Partners", provider: "greenhouse", board: "morsecorpcoop", group: "verified-us-swe" },
    { company: "Monogram", provider: "ashby", board: "monogram", group: "verified-us-swe" },
    { company: "Neuralink", provider: "greenhouse", board: "neuralink", group: "verified-us-swe" },
    { company: "Nova Talent", provider: "ashby", board: "nova-talent", group: "verified-us-swe" },
    { company: "Oligo Space", provider: "ashby", board: "oligo", group: "verified-us-swe" },
    { company: "Ontic", provider: "ashby", board: "Ontic", group: "verified-us-swe" },
    { company: "Pattern Data", provider: "greenhouse", board: "patterndata", group: "verified-us-swe" },
    { company: "Persona AI", provider: "ashby", board: "persona.ai", group: "verified-us-swe" },
    { company: "PlusAI", provider: "lever", board: "plus-2", group: "verified-us-swe" },
    { company: "PMG", provider: "greenhouse", board: "pmg", group: "verified-us-swe" },
    { company: "Prelim", provider: "ashby", board: "prelim", group: "verified-us-swe" },
    { company: "Probook", provider: "ashby", board: "probook", group: "verified-us-swe" },
    { company: "Quantcast", provider: "ashby", board: "quantcast", group: "verified-us-swe" },
    { company: "Relativity Space", provider: "greenhouse", board: "relativity", group: "verified-us-swe" },
    { company: "Rivet Industries", provider: "ashby", board: "rivet", group: "verified-us-swe" },
    { company: "Solid Power", provider: "greenhouse", board: "solidpower", group: "verified-us-swe" },
    { company: "SoloPulse", provider: "lever", board: "solopulseco", group: "verified-us-swe" },
    { company: "Spacial AI", provider: "ashby", board: "spacial", group: "verified-us-swe" },
    { company: "Synergy ECP", provider: "lever", board: "synergyecp", group: "verified-us-swe" },
    { company: "TELUS Digital", provider: "ashby", board: "telus-digital", group: "verified-us-swe" },
    { company: "Tenstorrent University", provider: "greenhouse", board: "tenstorrentuniversity", group: "verified-us-swe" },
    { company: "Terranova", provider: "ashby", board: "terranova", group: "verified-us-swe" },
    { company: "Tevora", provider: "lever", board: "tevora", group: "verified-us-swe" },
    { company: "The Nuclear Company", provider: "greenhouse", board: "thenuclearcompany", group: "verified-us-swe" },
    { company: "The Trade Desk", provider: "greenhouse", board: "thetradedesk", group: "verified-us-swe" },
    { company: "The Voleon Group", provider: "ashby", board: "voleon", group: "verified-us-swe" },
    { company: "TRM Labs", provider: "ashby", board: "trm-labs", group: "verified-us-swe" },
    { company: "Truveta", provider: "greenhouse", board: "truveta", group: "verified-us-swe" },
    { company: "Valstad", provider: "ashby", board: "valstad", group: "verified-us-swe" },
    { company: "Verkada", provider: "greenhouse", board: "verkada", group: "verified-us-swe" },
    { company: "Virtu Financial", provider: "greenhouse", board: "virtu", group: "verified-us-swe" },
    { company: "Vital Lyfe", provider: "ashby", board: "vital-lyfe", group: "verified-us-swe" },
    { company: "Voltus", provider: "lever", board: "voltus", group: "verified-us-swe" },
    { company: "Woven by Toyota", provider: "lever", board: "woven-by-toyota", group: "verified-us-swe" },
    { company: "xAI", provider: "greenhouse", board: "xai", group: "verified-us-swe" },
    { company: "Xsolla", provider: "lever", board: "xsolla", group: "verified-us-swe" },
    { company: "Zettabyte", provider: "ashby", board: "zettabyte-space", group: "verified-us-swe" },
    { company: "Zoox", provider: "lever", board: "zoox", group: "verified-us-swe" },
];
