const JOB_SKILLS = [
    ["Java", ["Java"]], ["Python", ["Python"]], ["C++", ["C++"]], ["C#", ["C#"]],
    ["Go", ["Golang", "Go"]], ["Ruby", ["Ruby"]], ["PHP", ["PHP"]], ["Swift", ["Swift"]],
    ["Kotlin", ["Kotlin"]], ["JavaScript", ["JavaScript"]], ["TypeScript", ["TypeScript"]],
    ["React", ["React"]], ["Angular", ["Angular"]], ["Vue.js", ["Vue.js", "Vue"]],
    ["Node.js", ["Node.js", "NodeJS"]], ["Express.js", ["Express.js", "ExpressJS"]],
    ["Django", ["Django"]], ["Flask", ["Flask"]], ["Spring Boot", ["Spring Boot"]],
    [".NET", [".NET"]], ["HTML", ["HTML"]], ["CSS", ["CSS"]], ["SQL", ["SQL"]],
    ["PostgreSQL", ["PostgreSQL", "Postgres"]], ["MySQL", ["MySQL"]], ["MongoDB", ["MongoDB"]],
    ["Redis", ["Redis"]], ["DynamoDB", ["DynamoDB"]], ["Snowflake", ["Snowflake"]],
    ["REST APIs", ["REST APIs", "REST API", "RESTful"]], ["GraphQL", ["GraphQL"]],
    ["Microservices", ["Microservices", "Microservice Architecture"]], ["AWS", ["AWS", "Amazon Web Services"]],
    ["Microsoft Azure", ["Microsoft Azure", "Azure"]], ["Google Cloud Platform", ["Google Cloud Platform", "Google Cloud", "GCP"]],
    ["Docker", ["Docker"]], ["Kubernetes", ["Kubernetes"]], ["Terraform", ["Terraform"]],
    ["Git", ["Git"]], ["CI/CD", ["CI/CD", "Continuous Integration", "Continuous Deployment"]],
    ["Jenkins", ["Jenkins"]], ["GitHub Actions", ["GitHub Actions"]], ["Playwright", ["Playwright"]],
    ["Jest", ["Jest"]], ["PyTest", ["PyTest"]], ["Kafka", ["Kafka"]], ["Spark", ["Apache Spark", "Spark"]],
    ["ETL", ["ETL"]], ["Data Modeling", ["Data Modeling"]], ["Data Pipelines", ["Data Pipelines", "Data Pipeline"]],
    ["Machine Learning", ["Machine Learning", "ML"]], ["Artificial Intelligence", ["Artificial Intelligence", "AI"]],
    ["Data Structures and Algorithms", ["Data Structures and Algorithms", "Algorithms"]],
    ["System Design", ["System Design"]], ["Cloud Computing", ["Cloud Computing", "Cloud Services"]],
    ["Agile", ["Agile"]], ["Scrum", ["Scrum"]], ["Communication", ["Communication"]],
    ["Teamwork", ["Teamwork", "Team Work"]], ["Problem Solving", ["Problem Solving", "Problem-Solving"]],
    ["Root Cause Analysis", ["Root Cause Analysis", "RCA"]],
    ["Incident Response", ["Incident Response", "Production Incidents"]],
    ["Troubleshooting", ["Troubleshooting", "Troubleshoot"]],
    ["Network Automation", ["Network Automation", "Network Automation Frameworks"]],
    ["Network Observability", ["Network Observability", "Network Monitoring", "Telemetry"]],
    ["Monitoring and Alerting", ["Monitoring and Alerting", "Dashboards and Alerting"]],
    ["Service Level Objectives", ["Service Level Objectives", "SLOs", "SLO"]],
    ["Mean Time to Detect", ["Mean Time to Detect", "MTTD"]],
    ["Mean Time to Recovery", ["Mean Time to Recovery", "MTTR"]],
    ["Runbooks", ["Runbooks", "Operational Runbooks"]],
    ["Ethernet", ["Ethernet", "Ethernet Fabrics"]],
    ["BGP", ["BGP"]], ["OSPF", ["OSPF"]], ["ECMP", ["ECMP"]],
    ["MLAG", ["MLAG"]], ["LACP", ["LACP"]], ["VRF", ["VRF", "VRFs"]],
    ["VLAN", ["VLAN", "VLANs"]], ["DNS", ["DNS"]], ["TCP/IP", ["TCP/IP", "TCP IP"]],
    ["Load Balancing", ["Load Balancing", "Load Balancer"]],
    ["Data Center Networking", ["Data Center Networking", "Data Centers"]],
    ["High Performance Computing", ["High Performance Computing", "HPC"]],
    ["GPU Computing", ["GPU Compute", "GPU Computing"]],
    ["Fiber Optics", ["Fiber Optics", "Fiber Optic"]],
    ["Transceivers", ["Transceivers"]], ["DAC/AOC Cables", ["DAC/AOC", "DAC AOC"]],
    ["100G Ethernet", ["100G"]], ["200G Ethernet", ["200G"]], ["400G Ethernet", ["400G"]], ["800G Ethernet", ["800G"]],
    ["VAST Data", ["VAST", "VAST Data"]], ["DDN", ["DDN"]],
    ["Distributed Storage", ["Distributed Storage"]], ["Storage Networking", ["Storage Networking"]],
    ["Colocation", ["Colocation", "Colo Providers"]],
    ["Hardware Lifecycle Management", ["Hardware Lifecycle", "Hardware Replacements"]],
    ["Change Management", ["Change Management", "Production Network Changes"]],
    ["Capacity Planning", ["Capacity Expansions", "Capacity Planning"]],
    ["On-call", ["On-call", "On Call Rotation"]],
    ["Linux", ["Linux"]], ["Bash", ["Bash", "Shell Scripting"]],
];

const EXTRA_SKILLS = [
    ['C',['C programming','programming in C']], ['Rust',['Rust']], ['R',['R programming','R language']],
    ['Scala',['Scala']],['Perl',['Perl']],['MATLAB',['MATLAB']],['Objective-C',['Objective-C']],
    ['Next.js',['Next.js','NextJS']],['NestJS',['NestJS','Nest.js']],['FastAPI',['FastAPI']],
    ['ASP.NET Core',['ASP.NET Core','ASP.NET Web API','.NET Core']],['Entity Framework',['Entity Framework']],
    ['Azure DevOps',['Azure DevOps']],['GitLab CI',['GitLab CI','GitLab CI/CD']],['Ansible',['Ansible']],
    ['Helm',['Helm']],['Argo CD',['Argo CD','ArgoCD']],['OpenTelemetry',['OpenTelemetry']],
    ['Prometheus',['Prometheus']],['Grafana',['Grafana']],['Datadog',['Datadog']],['Splunk',['Splunk']],
    ['OpenAI API',['OpenAI API','OpenAI APIs']],['Large Language Models',['large language models','LLMs','LLM']],
    ['Retrieval-Augmented Generation',['retrieval-augmented generation','retrieval augmented generation','RAG']],
    ['PyTorch',['PyTorch']],['TensorFlow',['TensorFlow']],['scikit-learn',['scikit-learn','sklearn']],
    ['LangChain',['LangChain']],['MLOps',['MLOps']],['NLP',['natural language processing','NLP']],
    ['Computer Vision',['computer vision']],['Vector Databases',['vector databases','vector database']],
    ['Airflow',['Airflow']],['dbt',['dbt']],['Databricks',['Databricks']],['Pandas',['Pandas']],['NumPy',['NumPy']],
    ['Power BI',['Power BI','PowerBI']],['Tableau',['Tableau']],['Excel',['Microsoft Excel','Excel']],
    ['Elasticsearch',['Elasticsearch']],['RabbitMQ',['RabbitMQ']],['SQL Server',['SQL Server','MSSQL']],
    ['Oracle',['Oracle Database','Oracle SQL']],['NoSQL',['NoSQL']],['DAX',['DAX']],
    ['Distributed Systems',['distributed systems','distributed system']],['Multithreading',['multithreading','multi-threading']],
    ['Concurrency',['concurrency','concurrent programming']],['Object-Oriented Programming',['object-oriented programming','OOP']],
    ['Functional Programming',['functional programming']],['Design Patterns',['design patterns']],
    ['Unit Testing',['unit testing','unit tests']],['Integration Testing',['integration testing','integration tests']],
    ['Test-Driven Development',['test-driven development','TDD']],['Mockito',['Mockito']],['JUnit',['JUnit']],
    ['Cypress',['Cypress']],['Selenium',['Selenium']],['Accessibility',['WCAG','web accessibility']],
    ['OAuth',['OAuth','OAuth2']],['SAML',['SAML']],['SOC 2',['SOC 2','SOC2']],['HIPAA',['HIPAA']],
    ['Figma',['Figma']],['User Research',['user research']],['Usability Testing',['usability testing']],
    ['Salesforce',['Salesforce']],['HubSpot',['HubSpot']],['SAP',['SAP']],['QuickBooks',['QuickBooks']],
    ['Financial Modeling',['financial modeling','financial modelling']],['GAAP',['GAAP']],['Budgeting',['budgeting']],
    ['Project Management',['project management']],['Stakeholder Management',['stakeholder management']],
    ['Requirements Gathering',['requirements gathering','requirements elicitation']],['Technical Writing',['technical writing']],
    ['A/B Testing',['A/B testing','AB testing']],['Statistical Analysis',['statistical analysis']],
    ['AutoCAD',['AutoCAD']],['SolidWorks',['SolidWorks']],['PLC Programming',['PLC programming']],
    ['Embedded Systems',['embedded systems']],['RTOS',['RTOS','real-time operating systems']],
];
const CATALOG = [...JOB_SKILLS, ...EXTRA_SKILLS.filter(([label])=>!JOB_SKILLS.some(([existing])=>existing===label))];
const aliasesFor = label => CATALOG.find(([key])=>key===label)?.[1] || [label];

module.exports={CATALOG,aliasesFor};

