import React, { useCallback, useEffect, useState } from "react";
import { getJobModeration, updateJobModeration } from "../../../connector";
import "./ManagementPages.scss";

const AdminJobModeration=()=>{
 const [jobs,setJobs]=useState([]); const [error,setError]=useState("");
 const load=useCallback(()=>getJobModeration().then(setJobs).catch(e=>setError(e.response?.data?.message||e.message)),[]);
 useEffect(()=>{void load();},[load]);
 const save=async(job,changes)=>{const updated=await updateJobModeration({jobUrl:job.job_url,externalJobId:job.external_job_id,jobTitle:job.job_title,company:job.company,provider:job.provider,permanentlyBlocked:job.permanently_blocked,adminTags:[],moderationStatus:job.moderation_status||"pending",resolutionNote:job.resolution_note,...changes});setJobs(current=>current.map(item=>item.job_url===job.job_url?{...item,...updated}:item));};
 const toggleAvailability=job=>void save(job,{permanentlyBlocked:!job.permanently_blocked,moderationStatus:job.permanently_blocked?"resolved_no_action":"permanently_blocked",resolutionNote:job.permanently_blocked?"Made available again by administrator":"Hidden again by administrator"});
 const autofill=job=>{const payload={jobUrl:job.job_url,jobTitle:job.job_title,company:job.company,provider:job.provider,externalJobId:job.external_job_id};const key=`jobpilot.autofill.${Date.now()}.${Math.random().toString(36).slice(2)}`;localStorage.setItem(key,JSON.stringify(payload));window.open(`/autofill?job=${encodeURIComponent(key)}`,"_blank","noopener,noreferrer");window.setTimeout(()=>localStorage.removeItem(key),60000);};
 return <main className="management-page"><div className="management-shell"><header className="management-heading"><h1>Reported jobs</h1><p>Administrator reports hide a job from every user. Restore a job here when it should become available again.</p></header>{error&&<p className="management-error">{error}</p>}<section className="management-list">{jobs.length?jobs.map(job=><article className="management-item moderation-item" key={job.job_url}><div className="management-item-copy"><div className="management-item-heading"><h2>{job.job_title||"Reported job"}</h2><span className={`feedback-status ${job.moderation_status||"pending"}`}>{job.permanently_blocked?"hidden":"available"}</span></div><p>{job.company||job.job_url} · {job.report_count||0} report(s)</p>{job.reasons?.length>0&&<details><summary>View report reasons</summary><ul>{job.reasons.map((reason,index)=><li key={`${reason}-${index}`}>{reason}</li>)}</ul></details>}{job.resolution_note&&<p><strong>Status note:</strong> {job.resolution_note}</p>}</div><div className="management-actions"><button className="primary" type="button" onClick={()=>autofill(job)}>Autofill</button><button className={job.permanently_blocked?"secondary":"danger"} type="button" onClick={()=>toggleAvailability(job)}>{job.permanently_blocked?"Make available":"Hide job"}</button></div></article>):<div className="management-panel">No reported jobs.</div>}</section></div></main>;
};
export default AdminJobModeration;
