import React,{useEffect,useState} from "react";
import {deleteJobPreference,getJobPreferences} from "../../../connector";
import "./ManagementPages.scss";
const JobPreferences=({state})=>{const[jobs,setJobs]=useState([]);const[error,setError]=useState("");
useEffect(()=>{getJobPreferences(state).then(setJobs).catch(e=>setError(e.response?.data?.message||e.message));},[state]);
const remove=async id=>{await deleteJobPreference(id);setJobs(current=>current.filter(job=>job.id!==id));};
const autofill=job=>{const payload={jobUrl:job.job_url,jobTitle:job.job_title,company:job.company,location:job.location,source:job.source,externalJobId:job.external_job_id};const key=`jobpilot.autofill.${Date.now()}.${Math.random().toString(36).slice(2)}`;localStorage.setItem(key,JSON.stringify(payload));window.open(`/autofill?job=${encodeURIComponent(key)}`,"_blank","noopener,noreferrer");window.setTimeout(()=>localStorage.removeItem(key),60000);};
return <main className="management-page"><div className="management-shell"><header className="management-heading"><h1>{state==="saved"?"Saved Jobs":"Blocked Jobs"}</h1><p>{state==="saved"?"Roles you want to revisit before applying.":"Jobs hidden from your active listings."}</p></header>{error&&<p>{error}</p>}<section className="management-list">{jobs.length?jobs.map(job=><article className="management-item" key={job.id}><div><h2>{job.job_title||"Job posting"}</h2><p>{job.company}{job.location?` · ${job.location}`:""}</p></div><div className="management-actions">{state==="saved"&&<button className="primary" onClick={()=>autofill(job)}>Autofill</button>}<a className={state==="saved"?"management-action-link secondary":"management-action-link"} href={job.job_url} target="_blank" rel="noreferrer">View job</a><button onClick={()=>remove(job.id)}>{state==="blocked"?"Unblock":"Remove"}</button></div></article>):<div className="management-panel">No {state} jobs yet.</div>}</section></div></main>};
export default JobPreferences;
