ALTER TABLE jobpilot.job_preferences
    ADD COLUMN IF NOT EXISTS employment_type TEXT,
    ADD COLUMN IF NOT EXISTS workplace_type TEXT,
    ADD COLUMN IF NOT EXISTS job_posted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS salary TEXT,
    ADD COLUMN IF NOT EXISTS provider TEXT,
    ADD COLUMN IF NOT EXISTS tags JSONB NOT NULL DEFAULT '[]'::JSONB,
    ADD COLUMN IF NOT EXISTS summary TEXT,
    ADD COLUMN IF NOT EXISTS requirements JSONB NOT NULL DEFAULT '[]'::JSONB;
